#!/bin/bash
# AI Mate - GitHub Setup and Render Deployment Commands
# Run this script or copy-paste commands one by one

set -e

echo "==================================="
echo "AI Mate Deployment Setup"
echo "==================================="
echo ""

# Check if GitHub CLI is installed
if command -v gh &> /dev/null; then
    echo "✅ GitHub CLI is installed"
    echo ""
    echo "OPTION 1: Fastest way using GitHub CLI"
    echo "----------------------------------------"
    echo "Run these commands:"
    echo ""
    echo "# Login to GitHub (if not already)"
    echo "gh auth login"
    echo ""
    echo "# Create repository and push (choose name you want)"
    echo "gh repo create ai-mate --public --source=. --remote=origin --push"
    echo ""
    echo "That's it! Your code will be on GitHub."
    echo ""
else
    echo "⚠️  GitHub CLI not installed"
    echo ""
    echo "To install GitHub CLI:"
    echo "  brew install gh"
    echo ""
fi

echo "OPTION 2: Manual GitHub Setup"
echo "----------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: ai-mate (or your choice)"
echo "3. Choose Public or Private"
echo "4. Do NOT initialize with README"
echo "5. Click 'Create repository'"
echo ""
echo "Then run these commands (replace YOUR-USERNAME):"
echo ""
echo "git remote add origin https://github.com/YOUR-USERNAME/ai-mate.git"
echo "git push -u origin main"
echo ""
echo "==================================="
echo ""

echo "AFTER PUSHING TO GITHUB:"
echo "----------------------------------------"
echo ""
echo "🚀 Deploy to Render:"
echo ""
echo "1. Go to: https://dashboard.render.com/"
echo "2. Sign up/login (use GitHub account for easy integration)"
echo "3. Click 'New +' → 'Blueprint'"
echo "4. Connect your GitHub account"
echo "5. Select the 'ai-mate' repository"
echo "6. Click 'Apply'"
echo "7. Wait 5-10 minutes for deployment"
echo "8. Done! You'll get URLs for frontend and backend"
echo ""
echo "==================================="
echo ""
echo "📖 Full instructions in: deploy-to-render.md"
echo ""
echo "Need help? Check:"
echo "  - deploy-to-render.md (step-by-step guide)"
echo "  - DEPLOYMENT.md (comprehensive guide)"
echo "  - DEPLOY_NOW.md (quick reference)"
echo ""
